# Generated by Django 2.2.6 on 2020-07-08 06:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Excursion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Название экскурсии')),
                ('description_short', models.TextField(blank=True, verbose_name='Короткое описание')),
                ('description_long', models.TextField(blank=True, verbose_name='Длинное описание')),
                ('lat', models.FloatField(blank=True, verbose_name='Широта')),
                ('lon', models.FloatField(blank=True, verbose_name='Долгота')),
            ],
        ),
    ]
