# Generated by Django 2.2.6 on 2020-07-13 07:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0002_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='image',
            old_name='title',
            new_name='img_title',
        ),
        migrations.AddField(
            model_name='image',
            name='excursion_title',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='places.Excursion'),
        ),
        migrations.AlterField(
            model_name='excursion',
            name='description_long',
            field=models.TextField(blank=True, null=True, verbose_name='Длинное описание'),
        ),
        migrations.AlterField(
            model_name='excursion',
            name='description_short',
            field=models.TextField(blank=True, null=True, verbose_name='Короткое описание'),
        ),
        migrations.AlterField(
            model_name='excursion',
            name='lat',
            field=models.FloatField(blank=True, null=True, verbose_name='Широта'),
        ),
        migrations.AlterField(
            model_name='excursion',
            name='lon',
            field=models.FloatField(blank=True, null=True, verbose_name='Долгота'),
        ),
        migrations.AlterField(
            model_name='image',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='', verbose_name='Название картинки'),
        ),
    ]
