# Generated by Django 2.2.6 on 2020-07-13 08:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0003_auto_20200713_1037'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='image',
            name='img_title',
        ),
    ]
