# Generated by Django 2.2.6 on 2020-07-14 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0004_remove_image_img_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='position',
            field=models.IntegerField(null=True, verbose_name='Позиция'),
        ),
    ]
